package Main;

import Models.oeuvre;
import Models.textile;
import Models.collection_t; // Don't forget to import the model
import Services.OeuvreService;
import Services.TextileService;
import Services.CollectionTService;

import java.sql.SQLException;
import java.util.List;

public class Test {
    public static void main(String[] args) {
        // Textile logic
        TextileService textileService = new TextileService();
        CollectionTService collectionTService = new CollectionTService();


        //for textile
        try {
            // Add a new textile (without specifying the ID, as it will be auto-generated)
            Integer collectionId = 2; // Example collectionId, adjust based on your logic
            String nom = "Textile Example";
            String type = "Fabric";
            String description = "A beautiful textile example.";
            String matiere = "Cotton";
            String couleur = "Red";
            String dimension = "30x30 cm";
            String createur = "Artist Name";
            String image = "image_path.jpg";
            String technique = "Weaving";
            int userId = 1; // Example userId, adjust based on your logic


// Create the new textile with the collection object
            textile nouvelleTextile = new textile(collectionId, nom, type, description,
                    matiere, couleur, dimension, createur,
                    image, technique, userId);

            // Add the new textile to the database
            textileService.add(nouvelleTextile);

            // Delete a textile by ID (assuming ID = 4 for this example)
            textile textileASupprimer = new textile();
            textileASupprimer.setId(4); // Specify the ID of the textile to delete
            textileService.delete(textileASupprimer);

            // Retrieve all textiles
            List<textile> textiles = textileService.getAll();
            for (textile t : textiles) {
                System.out.println(t.toString());
            }

        } catch (SQLException e) {
            System.out.println("SQL Error: " + e.getMessage());
        }
 // for collection_textile
        try {
            // Add a new collection (without specifying the ID, it will be auto-generated)
            String nom = "Collection Example";
            int userId = 1; // Adjust based on your logic
            String description = "A beautiful collection example.";

            // Create the new collection
            collection_t nouvelleCollection = new collection_t(nom, userId, description);

            // Add the new collection to the database
            collectionTService.add(nouvelleCollection);

            // Delete a collection by ID (assuming ID = 4 for this example)
            collection_t collectionASupprimer = new collection_t();
            collectionASupprimer.setId(4); // Specify the ID of the collection to delete
            collectionTService.delete(collectionASupprimer);

            // Retrieve all collections
            List<collection_t> collections = collectionTService.getAll();
            for (collection_t c : collections) {
                System.out.println(c.toString());
            }

        } catch (SQLException e) {
            System.out.println("SQL Error: " + e.getMessage());
        }
        // for oeuvre
        try {
            // Add a new oeuvre (without specifying the ID, as it will be auto-generated)
            Integer collectionId = 2; // Example collectionId, adjust based on your logic
            String nom = "Oeuvre Example";
            String type = "Ceramic";
            String description = "A beautiful ceramic artwork.";
            String matiere = "Clay";
            String couleur = "Blue";
            String dimension = "50x50 cm";
            String createur = "Artist Name";
            String image = "image_path.jpg";
            String categorie = "Modern Art";
            int userId = 1; // Example userId, adjust based on your logic

            // Set the ID as 0 for the new oeuvre (auto-generated by the DB)
            int id = 0;

            // Create the new oeuvre with the collection object
            oeuvre nouvelleOeuvre = new oeuvre(id, collectionId, userId, nom, type, description,
                    matiere, couleur, dimension, createur, image, categorie);

            // Add the new oeuvre to the database
            OeuvreService oeuvreService = new OeuvreService(); // Create an instance of your service
            oeuvreService.add(nouvelleOeuvre);

            // Delete an oeuvre by ID (assuming ID = 4 for this example)
            oeuvre oeuvreASupprimer = new oeuvre();
            oeuvreASupprimer.setId(4); // Specify the ID of the oeuvre to delete
            oeuvreService.delete(oeuvreASupprimer);

            // Retrieve all oeuvres
            List<oeuvre> oeuvres = oeuvreService.getAll();
            for (oeuvre o : oeuvres) {
                System.out.println(o.toString());
            }

        } catch (SQLException e) {
            System.out.println("SQL Error: " + e.getMessage());
        }




    }
}
